

<p align="justify">Previo a la creación del ACNUR en 1950, México como varios otros países fueron solidarios con apoyar a los españoles al ofrecerles asilo durante la Guerra Civil y la dictadura de Franco, así como de personas de otras naciones en la Segunda Guerra Mundial que se llevaba a cabo al mismo tiempo en Europa.</p>
<p align="justify">El 14 de diciembre de 1950 al término de la Segunda Guerra Mundial, se creó el ACNUR para ayudar a los millones de europeos desplazados por el conflicto. La Asamblea General de Naciones Unidas otorgó a ACNUR un mandato de tres años para completar sus labores y luego disolverse. Hoy, 69 años después, nuestra organización continúa con la labor de proteger y asistir a los refugiados alrededor del mundo. En México, el ACNUR tiene presencia desde 1982 y ha apoyado a los exiliados <p align="justify">de las dictaduras en América Latina en los años 1980 y de la Guerra Civil en Centroamérica en los años 1990.</p>
<p align="justify">A finales de los años 1930 y principios de los 1940, miles de españoles optaron por huir debido a la violencia y la persecución que se vivía en España durante la Guerra Civil y el franquismo. De estos refugiados se estima que la inmigración de intelectuales o élite español se conformaba de aproximadamente un 25% del total (5,500 aproximadamente). A este fenómeno también se calificó como el exilio republicano español debido a que estaban vinculados al gobierno republicado derrotado.</p>
<p align="justify">Los Gobiernos de las Repúblicas mexicana y española habían preparado el asilo para un gran número de españoles, cuyo desembarco data del 13 de junio de 1939, fecha en que el barco Sinaia tocó tierra en Veracruz. Los barcos Mexique, Ipanema, Orinoco, Flandre o Nyassa también significan para muchos de ellos la salvación en su nuevo país de acogida: México.</p>
<p align="justify">Se destaca también que llegaron además obreros, campesinos, así como militares, marinos y pilotos, hombres de Estado, economistas y empresarios, todos ellos vinculados al Gobierno republicano derrotado en la guerra.</p>
<p align="justify">Gracias al apoyo del Ateneo español, ACNUR accedió a varios exiliados para relatar sus historias.</p>
<p align="justify">Los barcos que trasladaron a los españoles a México fueron: el Sinaia (23 de mayo de 1939, con 1800 personas), el Ipanema (7 de julio de 1939 con 998 personas), el Mexique (27 de julio de 1939 con 2200 personas), el Flandra (7 de noviembre de 1939 con 273 personas), el Nyassa (22 de mayo de 1942 con 863 personas) y el Serpa Pinto II (1 de octubre de 1942 con 36 personas).</p>
